"""The eye-care tip pool for Mimi Helen Bot — written in Dr Helen's voice.

Kept in its own module so the big list doesn't clutter ``content.py``. Selection
(shuffled per day, no same-day repeats) lives in ``content.py``.

Rules for entries: keep each a single short line, all lowercase Singlish in her
voice, HTML-safe for Telegram (escape ``&`` as ``&amp;``; no raw ``<``/``>``),
and every line distinct. General eye-care info only — never diagnosis; the bot
always defers to her real eye doctor for anything specific.
"""

from __future__ import annotations

from typing import List

EYE_CARE_TIPS: List[str] = [
    # ---- eyedrop technique ----
    "20-20-20 ah: every 20 min, look 20 feet away for 20 sec. your eyes not iron made 👁️",
    "one drop is enough. the eye can't hold more, the rest just rolls out — don't waste.",
    "after the drop, close your eyes gently ~1 min. don't blink blink blink, it pumps the drop out.",
    "press the inner corner of your eye after drops. less drains into your throat, works better.",
    "shake the bottle if the label says so. some drops settle — you want the full strength.",
    "tilt head back, look up, pull the lower lid into a little pocket, then drop. easy.",
    "don't let the bottle tip touch your eye or lashes. that's how it gets contaminated.",
    "two different drops? wait 5 min between them, or the second washes out the first.",
    "drops first, ointment last if you have both. liquid before grease.",
    "missed a dose? just take the next one. don't double up to 'catch up'.",
    "can't aim? do it lying down, or in front of a mirror. no shame, whatever works.",
    "stings then tears a lot for a second? normal. don't panic and don't redo it.",
    "finish the full course. don't stop just because your eye feels better already.",
    "preservative-free vials: use within a day of opening, then throw. don't be stingy with your eyes.",
    "wash your hands before every drop. every single time. germs love your eyes.",
    "write the open-date on the bottle so you know when 4 weeks is up.",
    "store as directed — some drops must go in the fridge. read the box.",
    "cold drops from the fridge actually feel quite shiok on tired eyes.",
    "warm the bottle in your hand for a sec if cold drops make you flinch.",
    "one eye or both? do exactly what's prescribed. don't share a drop 'to save'.",
    # ---- drop hygiene & storage ----
    "don't share your eyedrops with anyone. infection passes bottle to bottle.",
    "keep the cap on tight and clean. don't let it roll on the table then put back.",
    "expired drops — throw. they lose strength and can grow bugs. not worth it.",
    "travelling? keep your drops in your hand-carry. cargo hold gets too hot and cold.",
    "if the drop looks cloudy or changed colour, don't use it. bin it.",
    "keep the leaflet that comes with your drops. it answers a lot of questions.",
    "refill before the last few drops, not after you've run out.",
    "not sure what a drop is for? ask your pharmacist. that's literally their job.",
    "more drops is not better. stick to the prescribed number, no freelancing.",
    "keep a spare bottle at work or in your bag. no 'left it at home' excuse.",
    # ---- dry eye & environment ----
    "dry, gritty, sandy feeling? classic dry eye. lubricating drops plus less screen helps.",
    "blink fully. half-blinks don't spread your tears. squeeze gently sometimes.",
    "aircon blasting your face dries your eyes out fast. point the vent away.",
    "ceiling fan straight on your face all night = waking up with dry, stuck eyes.",
    "small humidifier in an aircon room helps your eyes a lot. or just a bowl of water.",
    "drink water lah. a dehydrated body makes dry eyes. sip through the day.",
    "warm compress 5-10 min for tired, heavy eyes. unblocks the little oil glands.",
    "gently massage the eyelid after a warm compress. helps the oil flow.",
    "wipe your lid margins with a clean warm cloth if they get crusty. lid hygiene.",
    "flights are super dry. bring lubricating drops on the plane.",
    "staring at a book for hours dries eyes too, not just screens. blink breaks still apply.",
    "smoke and haze irritate the eyes. close the windows on bad-air days.",
    "wind in your face on a bike dries eyes — wraparound shades help.",
    "humid bathroom steam can soothe dry eyes for a few minutes. cheap trick.",
    "don't fight dry eye by rubbing. rubbing makes it worse, not better.",
    "eyes feel dry by evening? you're probably blinking too little. notice it, blink more.",
    "gel drops last longer at night; thin drops for daytime. ask which suits you.",
    "tears evaporate faster in fans and aircon. lubricate before, not after it hurts.",
    "if your eyes water a LOT, sometimes it's dry eye over-reacting. get it checked.",
    "dry eye flaring? cut screen time for a day and see how much better it feels.",
    # ---- screens & digital habits ----
    "keep the computer screen slightly below eye level. less eye surface exposed = less dryness.",
    "screen an arm's length away. you don't need to paste your face on it.",
    "bump up the text size. squinting tires your eyes and makes you blink less.",
    "match your screen brightness to the room. too bright or too dark both strain.",
    "use dark mode at night if it's more comfortable. whatever stops the squint.",
    "every 20 min, look far. set a timer if you keep forgetting — no excuse.",
    "don't sit with a bright window right behind or in front of your screen. glare.",
    "a matte screen or anti-glare cover cuts reflections. easier on the eyes.",
    "take a proper screen break every hour. stand, walk, look out the window.",
    "doom-scrolling in bed in the dark? worst combo for your eyes. lights on at least.",
    "kids on devices: 20-20-20 for them too, and more outdoor time for their eyes.",
    "more outdoor daylight slows short-sightedness in children. send them out to play.",
    "blue light won't blind you, but late screens wreck sleep, which wrecks your eyes.",
    "cut the screen about an hour before bed. your eyes and your sleep both win.",
    "reading in a moving car or bus strains the eyes. give it a rest.",
    "phone too close while lying down? hold it further, or you'll strain.",
    "long gaming session? same rules — breaks, blinks, and don't forget to drink water.",
    "set your phone to auto-dim at night. your eyes don't need full blast at 11pm.",
    "tired, dry eyes after work = a sign you went too hard on screens. ease up.",
    "look up from the screen and yawn-stretch your eyes now and then. feels good.",
    "two monitors? keep them at the same height and distance. no neck-craning.",
    "scrolling makes you blink even less than reading. blink on purpose.",
    "give your eyes one screen-light evening a week. they'll feel the difference.",
    # ---- sleep & rest ----
    "good sleep = happier eyes. aim for 7-8 hours. your eyes repair overnight.",
    "don't sleep in contact lenses. the cornea needs to breathe at night.",
    "take off eye makeup before bed. sleeping in mascara is asking for trouble.",
    "wake with stuck or crusty eyes daily? mention it to your eye doctor.",
    "an eye mask helps if light keeps your eyes from properly resting.",
    "nap with eyes fully closed in a dark room. real rest for tired eyes.",
    "screens off, lights low before bed — your eyes wind down too.",
    "if you sleep with your eyes slightly open, tell your doctor — it dries them out.",
    "rest is not lazy. your eyes literally heal when you let them rest.",
    "puffy morning eyes? less salt at night and a cool compress helps.",
    # ---- UV / outdoors ----
    "going out? sunglasses. UV is real, and it adds up over the years 🕶️",
    "buy shades with proper UV400, not just a dark tint. fake dark ones are worse.",
    "wraparound styles block side glare and wind. good for outdoors.",
    "a wide-brim hat plus shades = double protection on a sunny day.",
    "UV is strong even on cloudy days and reflects off water and sand. still wear shades.",
    "kids need UV protection too. start the sunglasses habit young.",
    "never stare at the sun, and never at an eclipse without proper filters.",
    "snow and bright beaches bounce a lot of UV. protect up.",
    "midday sun is the harshest. shades and shade between 11 and 3.",
    "cheap toy sunglasses with no UV can be worse than none — pupils open, more UV in.",
    # ---- nutrition & hydration ----
    "eat your greens — spinach, kale. lutein is good for the retina.",
    "carrots aren't a myth: vitamin A really does matter for your eyes.",
    "oily fish like salmon or sardines twice a week — omega-3 helps dry eye.",
    "colourful veg and fruit = antioxidants your eyes love. eat the rainbow.",
    "eggs have lutein and zeaxanthin too. good for the macula.",
    "too much sugar long-term harms the tiny eye blood vessels. go easy.",
    "stay hydrated for your tear film. water over sweet drinks.",
    "citrus and nuts (vitamin C and E) support eye health. snack smart.",
    "zinc from nuts, beans and seeds helps your body use vitamin A.",
    "crash diets starve your eyes of nutrients too. eat properly lah.",
    "alcohol dehydrates you and your eyes. moderate, and drink water alongside.",
    "too much caffeine can dry you out. balance every kopi with water.",
    "orange and yellow veg (pumpkin, capsicum) are loaded with eye-friendly stuff.",
    "berries and dark chocolate antioxidants are good for you AND your eyes. yay.",
    "a balanced plate beats any single 'eye supplement' — food first.",
    "don't smoke. it harms the retina and worsens dry eye. cut down, eyes will thank you.",
    "heavy drinking nights = red, puffy, dry eyes next day. you already know.",
    "green tea has antioxidants that reach the eye tissues. nice excuse for a cup.",
    # ---- contact lenses ----
    "contacts: wash and dry your hands before touching them. always.",
    "don't top up old solution. fresh solution every time, fully covering the lens.",
    "never use water or saliva on contacts. that's how bad infections start.",
    "follow the replacement schedule — dailies daily, monthlies monthly. don't stretch it.",
    "take contacts out before drops; wait ~15 min before putting them back, unless told otherwise.",
    "red, painful eye with contacts? take them out NOW and get it checked. don't wait.",
    "give your eyes contact-free days. glasses are not a step down.",
    "don't swim or shower in contacts. waterborne bugs love the cornea.",
    "rub-and-rinse your lenses even if it says 'no rub'. cleans off the gunk.",
    "store the lens case clean, air-dry it, and replace it every ~3 months.",
    "contacts feel dry by evening? you may be over-wearing. cut the hours.",
    "get lenses with a proper fitting and prescription. no random cosmetic ones online.",
    "coloured/cosplay lenses still need real lens hygiene. they're not toys.",
    # ---- makeup & hygiene ----
    "remove eye makeup gently. tugging the lids ages them and irritates eyes.",
    "don't line your inner waterline with kohl daily — it blocks the oil glands.",
    "replace mascara every ~3 months. old tubes grow bacteria.",
    "never share eye makeup or brushes. pink eye spreads that way.",
    "skip eye makeup if your eye is already red or irritated. let it settle.",
    "false-lash glue can irritate — patch test, and never sleep in them.",
    "clean your makeup brushes regularly. dirty brushes = dirty eyes.",
    "take makeup off the same night, every night. no 'too tired' excuse.",
    "glitter and loose powder near the eye can scratch. careful.",
    "expired eye cream or makeup near the eye? toss it. eyes are sensitive.",
    # ---- no rubbing / irritation ----
    "eyes itchy? don't rub. rubbing scratches the surface and spreads germs.",
    "allergy itch? cool compress and ask about antihistamine drops. not rubbing.",
    "something flew in? don't rub — blink lots, flush with clean water or saline.",
    "rubbing hard over years can warp the cornea. hands off, seriously.",
    "kids rub a lot — gently remind them, give a cool cloth instead.",
    "tired eyes want a rub so badly — palm them with clean warm hands instead.",
    "chemical splash? flush with water 15+ min and get help fast. don't rub.",
    "scratchy after the gym? could be sweat or sunscreen. rinse, don't rub.",
    "stye coming up? warm compress, leave it alone, don't squeeze it.",
    "pink, gluey and spreading? likely conjunctivitis — see a doctor, wash hands, don't share towels.",
    # ---- lifestyle & general health ----
    "move your body — exercise improves blood flow, good for the eyes too.",
    "manage your blood pressure. high BP quietly damages the retina.",
    "diabetic? control your sugar and do your yearly retina scan. non-negotiable.",
    "stress and no sleep show up as eye twitches. rest, hydrate, cut the caffeine.",
    "sit up straight at your desk — slouching into the screen strains eyes and neck.",
    "good room lighting for reading. don't squint in the dark like that.",
    "position your desk lamp to the side, not glaring into your eyes.",
    "keep your weight and cholesterol in check — eye blood vessels care about that too.",
    "a twitchy eyelid for a day or two is usually tiredness. weeks? get it checked.",
    "wash your hands often through the day — you touch your eyes more than you think.",
    # ---- protection ----
    "DIY, drilling, mowing, cutting? safety goggles. one flying chip can cost an eye.",
    "opening champagne or using cleaning sprays — point away from your face.",
    "racquet sports or squash? protective eyewear. fast ball, small socket.",
    "gardening near branches at eye level — wear glasses. pokes are no joke.",
    "cooking with hot oil splatter — stand back, your eyes are right there.",
    "welding, lasers or strong lights at work? wear the proper eye protection. no shortcuts.",
    "kids with toys that shoot or poke — supervise. eye injuries happen fast.",
    "fireworks and sparklers — keep a safe distance, especially for little ones.",
    "carrying chemicals or strong cleaners? goggles, and know where the nearest tap is.",
    "sports with a ball to the face risk? a guard is cheaper than an eye.",
    # ---- check-ups & prevention ----
    "go for an eye check every 1-2 years even if you see fine. silent problems exist.",
    "over 40? glaucoma screening matters — it steals vision with no warning.",
    "family history of glaucoma or retinal disease? tell your eye doctor, check earlier.",
    "high short-sightedness means higher retina risks — keep up your check-ups.",
    "kids squinting, sitting close to the TV, or getting headaches? get their eyes tested.",
    "one eye seeing worse without you noticing? that's why we check each eye separately.",
    "keep your glasses prescription updated. straining through old lenses tires you.",
    "clean glasses with proper spray and microfibre, not your shirt. scratches blur vision.",
    "anti-glare coating on glasses helps a lot for night driving and screens.",
    "keep a spare pair of glasses. don't squint for a week when one breaks.",
    "don't grab strong reading glasses off the rack blindly — get the right power.",
    "pregnant and vision changing a lot? mention it at your check-ups.",
    "menopause can worsen dry eye — common, and treatable. speak up.",
    "thyroid issues can affect the eyes. bulging or pressure feeling? get checked.",
    "night-driving glare bothering you more lately? get your eyes (and cataracts) checked.",
    # ---- medication sense ----
    "redness-relief 'whitening' drops daily can cause rebound redness. don't rely on them.",
    "don't self-medicate with someone else's leftover eye drops. wrong drug, wrong eye.",
    "antibiotic drops are for infections, not every red eye. get it diagnosed first.",
    "steroid eye drops need supervision — long use can raise eye pressure. don't extend on your own.",
    "glaucoma drops: never skip. pressure control is a daily job, no off days.",
    "artificial tears you can use freely for comfort — preservative-free if often.",
    "if a drop stings every single time, tell your doctor — there may be a gentler one.",
    "some pills cause dry eyes as a side effect. ask if yours might.",
    "keep a simple list of all your eye meds for appointments. saves time.",
    "ran out of a daily eye medicine? get it refilled today, not 'later'.",
    # ---- red-flag symptoms ----
    "sudden blurring, double vision, or a 'curtain' over your sight = go to eye A&amp;E now.",
    "sudden vision loss in one eye — treat it as an emergency. minutes matter.",
    "flashing lights with a shower of new floaters — retina warning. don't delay.",
    "halos around lights with eye pain and nausea — could be acute glaucoma. emergency.",
    "chemical or metal in the eye, or a deep poke — go straight to A&amp;E.",
    "eye swelling shut, with fever, or it won't move properly — get help fast, not tomorrow.",
    "a red eye with real pain and light sensitivity is not 'nothing'. get it seen.",
    "straight lines look wavy or bent? don't ignore — get a macula check soon.",
    "a blind spot growing in the centre of your vision — see a retina specialist quickly.",
    "one pupil suddenly bigger, a droopy lid, or new double vision — get urgent help.",
    "if a drop ever causes severe pain or a vision drop, stop and get reviewed.",
    "new floaters after eye surgery or an injury — call your eye doctor, don't assume.",
    # ---- post-procedure ----
    "post-surgery: no rubbing, no swimming, and use your drops exactly as scheduled.",
    "wear your eye shield at night after surgery so you don't rub in your sleep.",
    "after laser or surgery, sunglasses outdoors — your eyes are extra light-sensitive.",
    "stick to your post-op review dates. healing needs checking, even if it feels fine.",
    "no eye makeup for a while after surgery — wait until your doctor says ok.",
    # ---- habit & encouragement ----
    "set your drops next to your toothbrush. pair it with a habit you already do.",
    "phone alarms for each dose. your future eyes will thank present you.",
    "tick it off when you do it. small wins build the habit.",
    "routine beats motivation. same times every day, until it's automatic.",
    "travelling across time zones? dose by the clock at your destination, ask if unsure.",
    "you only get two eyes. baby them a little. it's worth it 🤍",
    "small daily habits beat heroic once-a-year effort. keep going.",
    "consistency is the magic. one drop at a time, one day at a time.",
    "proud of you for keeping up with this. your eyes are in good hands 💧",
    "future-you, reading comfortably at 70, says thank you.",
    "an eye habit done 'good enough' daily beats 'perfect' never. just do it.",
    "when in doubt about anything eye-related, ask the professional, not the internet.",
    "you've got this. eyes happy, you happy. now go do your drops 😉",
]
